<?xml version="1.0" encoding="utf-8"?><Database Name="DemPreparation" Class="DemPreparationContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DemPreparation.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MilSpace.DataAccess.Properties.Settings" SettingsPropertyName="DemPreparationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MilSpace_S1PairCoh" Member="S1PairCoherences" AccessModifier="Internal">
    <Type Name="S1PairCoherence" AccessModifier="Internal">
      <Column Name="idrow" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idSceneBase" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="idScentSlave" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="fmean" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fdeviation" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fmin" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fmax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dto" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soper" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSpace_S1SRC" Member="S1Sources" AccessModifier="Internal">
    <Type Name="S1Sources" AccessModifier="Internal">
      <Column Name="idrow" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idscene" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="extend" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dttime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nburst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="norbit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dto" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soper" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSpace_SentinelProduct" Member="S1SentinelProducts">
    <Type Name="S1SentinelProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Uuid" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Identifier" Type="System.String" DbType="NChar(38) NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Instrument" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Footprint" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JTSfootprint" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PassDirection" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RelativeOrbit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrbitNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SliceNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Wkt" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="sOper" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Dto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TileName" Storage="_TilName" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Downloaded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MilSpace_S1TilesCover" Member="S1TilesCoverage_1s" AccessModifier="Internal">
    <Type Name="S1TilesCoverage_1" AccessModifier="Internal">
      <Column Name="idrow" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuaziTileName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sOper" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEMFilePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SceneName" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Wkt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MilSpace_S1TilesCover" Member="S1TilesCoverages" AccessModifier="Internal">
    <Type Name="S1TilesCoverage" AccessModifier="Internal">
      <Column Name="idrow" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Wkt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QuaziTileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Dto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sOper" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEMFilePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SceneName" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>