<?xml version="1.0" encoding="utf-8"?><Database Name="MilSpaceApp" Class="MilSpaceVisibility" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=MilSpaceApp;Integrated Security=True" SettingsObjectName="MilSpace.DataAccess.Properties.Settings" SettingsPropertyName="MilSpaceAppConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MilSp_Visible_ResultIOP" Member="MilSp_Visible_ResultIOPs">
    <Type Name="MilSp_Visible_ResultIOP">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idOPRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idIOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HAbs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_InstantObservationPoint" Member="MilSp_Visible_InstantObservationPoints">
    <Type Name="MilSp_Visible_InstantObservationPoint">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idIOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDOP" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="HAbs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_Results" Member="MilSp_Visible_Results">
    <Type Name="MilSp_Visible_Result">
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeRez" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ishare" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dto" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soper" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultsCover" Member="MilSp_Visible_ResultsCovers">
    <Type Name="MilSp_Visible_ResultsCover">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCover" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LnkToCover" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ColorCover" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoDataCover" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_CL_TypeOP" Member="MilSp_CL_TypeOPs">
    <Type Name="MilSp_CL_TypeOP">
      <Column Name="objectid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeOP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ObjectsObservation_R" Member="MilSp_Visible_ObjectsObservation_Rs">
    <Type Name="MilSp_Visible_ObjectsObservation_R">
      <Column Name="idobjects" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ObservPoints_P" Member="MilSp_Visible_ObservPoints_Ps">
    <Type Name="MilSp_Visible_ObservPoints_P">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultOO" Member="MilSp_Visible_ResultOOs">
    <Type Name="MilSp_Visible_ResultOO">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultQuality" Member="MilSp_Visible_ResultQualities">
    <Type Name="MilSp_Visible_ResultQuality">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idResQual" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDOORes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDOPRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeQual" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EvalQual" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultIOP" Member="MilSp_Visible_ResultIOP1s">
    <Type Name="MilSp_Visible_ResultIOP1">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>