#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilSpace.DataAccess.Definition
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DNOEGDB")]
	public partial class MilSpaceStorageContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMilSp_Session(MilSp_Session instance);
    partial void UpdateMilSp_Session(MilSp_Session instance);
    partial void DeleteMilSp_Session(MilSp_Session instance);
    partial void InsertMilSp_Profile(MilSp_Profile instance);
    partial void UpdateMilSp_Profile(MilSp_Profile instance);
    partial void DeleteMilSp_Profile(MilSp_Profile instance);
    partial void InsertVisiblilityObservPoint11(VisiblilityObservPoint11 instance);
    partial void UpdateVisiblilityObservPoint11(VisiblilityObservPoint11 instance);
    partial void DeleteVisiblilityObservPoint11(VisiblilityObservPoint11 instance);
    partial void InsertVisiblilityObservPoint(VisiblilityObservPoint instance);
    partial void UpdateVisiblilityObservPoint(VisiblilityObservPoint instance);
    partial void DeleteVisiblilityObservPoint(VisiblilityObservPoint instance);
    #endregion
		
		public MilSpaceStorageContext() :
                //base(global::MilSpace.DataAccess.Properties.Settings.Default.DNOEGDBConnectionString, mappingSource)
                base(global::MilSpace.DataAccess.Properties.Settings.Default.MilSpaceAppConnectionString, mappingSource)
        {
			OnCreated();
		}
		
		public MilSpaceStorageContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		internal System.Data.Linq.Table<MilSp_Session> MilSp_Sessions
		{
			get
			{
				return this.GetTable<MilSp_Session>();
			}
		}
		
		internal System.Data.Linq.Table<MilSp_Profile> MilSp_Profiles
		{
			get
			{
				return this.GetTable<MilSp_Profile>();
			}
		}
		
		public System.Data.Linq.Table<VisiblilityObservPoint11> VisiblilityObservPoint11s
		{
			get
			{
				return this.GetTable<VisiblilityObservPoint11>();
			}
		}
		
		public System.Data.Linq.Table<VisiblilityObservPoint> VisiblilityObservPoints
		{
			get
			{
				return this.GetTable<VisiblilityObservPoint>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MilSp_Session")]
	internal partial class MilSp_Session : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private int _ProfileId;
		
		private EntityRef<MilSp_Profile> _MilSp_Profile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnProfileIdChanging(int value);
    partial void OnProfileIdChanged();
    #endregion
		
		public MilSp_Session()
		{
			this._MilSp_Profile = default(EntityRef<MilSp_Profile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProfileId
		{
			get
			{
				return this._ProfileId;
			}
			set
			{
				if ((this._ProfileId != value))
				{
					if (this._MilSp_Profile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfileIdChanging(value);
					this.SendPropertyChanging();
					this._ProfileId = value;
					this.SendPropertyChanged("ProfileId");
					this.OnProfileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MilSp_Profile_MilSp_Session", Storage="_MilSp_Profile", ThisKey="ProfileId", OtherKey="idRow", IsForeignKey=true)]
		public MilSp_Profile MilSp_Profile
		{
			get
			{
				return this._MilSp_Profile.Entity;
			}
			set
			{
				MilSp_Profile previousValue = this._MilSp_Profile.Entity;
				if (((previousValue != value) 
							|| (this._MilSp_Profile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MilSp_Profile.Entity = null;
						previousValue.MilSp_Sessions.Remove(this);
					}
					this._MilSp_Profile.Entity = value;
					if ((value != null))
					{
						value.MilSp_Sessions.Add(this);
						this._ProfileId = value.idRow;
					}
					else
					{
						this._ProfileId = default(int);
					}
					this.SendPropertyChanged("MilSp_Profile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MilSp_Profile")]
	internal partial class MilSp_Profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRow;
		
		private string _ProfileName;
		
		private string _ProfileData;
		
		private bool _Shared;
		
		private string _Creator;
		
		private System.DateTime _Created;
		
		private EntitySet<MilSp_Session> _MilSp_Sessions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRowChanging(int value);
    partial void OnidRowChanged();
    partial void OnProfileNameChanging(string value);
    partial void OnProfileNameChanged();
    partial void OnProfileDataChanging(string value);
    partial void OnProfileDataChanged();
    partial void OnSharedChanging(bool value);
    partial void OnSharedChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreatedChanging(System.DateTime value);
    partial void OnCreatedChanged();
    #endregion
		
		public MilSp_Profile()
		{
			this._MilSp_Sessions = new EntitySet<MilSp_Session>(new Action<MilSp_Session>(this.attach_MilSp_Sessions), new Action<MilSp_Session>(this.detach_MilSp_Sessions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRow", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idRow
		{
			get
			{
				return this._idRow;
			}
			set
			{
				if ((this._idRow != value))
				{
					this.OnidRowChanging(value);
					this.SendPropertyChanging();
					this._idRow = value;
					this.SendPropertyChanged("idRow");
					this.OnidRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileName", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string ProfileName
		{
			get
			{
				return this._ProfileName;
			}
			set
			{
				if ((this._ProfileName != value))
				{
					this.OnProfileNameChanging(value);
					this.SendPropertyChanging();
					this._ProfileName = value;
					this.SendPropertyChanged("ProfileName");
					this.OnProfileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileData", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ProfileData
		{
			get
			{
				return this._ProfileData;
			}
			set
			{
				if ((this._ProfileData != value))
				{
					this.OnProfileDataChanging(value);
					this.SendPropertyChanging();
					this._ProfileData = value;
					this.SendPropertyChanged("ProfileData");
					this.OnProfileDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shared", DbType="Bit NOT NULL")]
		public bool Shared
		{
			get
			{
				return this._Shared;
			}
			set
			{
				if ((this._Shared != value))
				{
					this.OnSharedChanging(value);
					this.SendPropertyChanging();
					this._Shared = value;
					this.SendPropertyChanged("Shared");
					this.OnSharedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime NOT NULL")]
		public System.DateTime Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MilSp_Profile_MilSp_Session", Storage="_MilSp_Sessions", ThisKey="idRow", OtherKey="ProfileId")]
		public EntitySet<MilSp_Session> MilSp_Sessions
		{
			get
			{
				return this._MilSp_Sessions;
			}
			set
			{
				this._MilSp_Sessions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MilSp_Sessions(MilSp_Session entity)
		{
			this.SendPropertyChanging();
			entity.MilSp_Profile = this;
		}
		
		private void detach_MilSp_Sessions(MilSp_Session entity)
		{
			this.SendPropertyChanging();
			entity.MilSp_Profile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MILSP_VISIBLE_OBSERVPOINTS")]
	public partial class VisiblilityObservPoint11 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OBJECTID;
		
		private string _soper;
		
		private string _idOP;
		
		private string _TitleOP;
		
		private string _TypeOP;
		
		private string _sGroup;
		
		private string _saffiliation;
		
		private System.Nullable<int> _ishare;
		
		private System.Nullable<decimal> _XWGS;
		
		private System.Nullable<decimal> _YWGS;
		
		private System.Nullable<decimal> _HRel;
		
		private System.Nullable<decimal> _AzimuthB;
		
		private System.Nullable<decimal> _AzimuthE;
		
		private System.Nullable<decimal> _AnglMinH;
		
		private System.Nullable<decimal> _AnglMaxH;
		
		private System.Nullable<decimal> _AzimuthMainAxis;
		
		private System.Nullable<decimal> _AngFrameH;
		
		private System.Nullable<decimal> _AnglFrameV;
		
		private System.Nullable<decimal> _AnglCameraRotationH;
		
		private System.Nullable<decimal> _AnglCameraRotationV;
		
		private double _AvailableHeightUpper;
		
		private double _AvailableHeightLover;
		
		private System.Nullable<System.DateTime> _dto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTIDChanging(int value);
    partial void OnOBJECTIDChanged();
    partial void OnsoperChanging(string value);
    partial void OnsoperChanged();
    partial void OnidOPChanging(string value);
    partial void OnidOPChanged();
    partial void OnTitleOPChanging(string value);
    partial void OnTitleOPChanged();
    partial void OnTypeOPChanging(string value);
    partial void OnTypeOPChanged();
    partial void OnsGroupChanging(string value);
    partial void OnsGroupChanged();
    partial void OnsaffiliationChanging(string value);
    partial void OnsaffiliationChanged();
    partial void OnishareChanging(System.Nullable<int> value);
    partial void OnishareChanged();
    partial void OnXWGSChanging(System.Nullable<decimal> value);
    partial void OnXWGSChanged();
    partial void OnYWGSChanging(System.Nullable<decimal> value);
    partial void OnYWGSChanged();
    partial void OnHRelChanging(System.Nullable<decimal> value);
    partial void OnHRelChanged();
    partial void OnAzimuthBChanging(System.Nullable<decimal> value);
    partial void OnAzimuthBChanged();
    partial void OnAzimuthEChanging(System.Nullable<decimal> value);
    partial void OnAzimuthEChanged();
    partial void OnAnglMinHChanging(System.Nullable<decimal> value);
    partial void OnAnglMinHChanged();
    partial void OnAnglMaxHChanging(System.Nullable<decimal> value);
    partial void OnAnglMaxHChanged();
    partial void OnAzimuthMainAxisChanging(System.Nullable<decimal> value);
    partial void OnAzimuthMainAxisChanged();
    partial void OnAngFrameHChanging(System.Nullable<decimal> value);
    partial void OnAngFrameHChanged();
    partial void OnAnglFrameVChanging(System.Nullable<decimal> value);
    partial void OnAnglFrameVChanged();
    partial void OnAnglCameraRotationHChanging(System.Nullable<decimal> value);
    partial void OnAnglCameraRotationHChanged();
    partial void OnAnglCameraRotationVChanging(System.Nullable<decimal> value);
    partial void OnAnglCameraRotationVChanged();
    partial void OnAvailableHeightUpperChanging(double value);
    partial void OnAvailableHeightUpperChanged();
    partial void OnAvailableHeightLoverChanging(double value);
    partial void OnAvailableHeightLoverChanged();
    partial void OndtoChanging(System.Nullable<System.DateTime> value);
    partial void OndtoChanged();
    #endregion
		
		public VisiblilityObservPoint11()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this.OnOBJECTIDChanging(value);
					this.SendPropertyChanging();
					this._OBJECTID = value;
					this.SendPropertyChanged("OBJECTID");
					this.OnOBJECTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soper", DbType="NVarChar(50)")]
		public string soper
		{
			get
			{
				return this._soper;
			}
			set
			{
				if ((this._soper != value))
				{
					this.OnsoperChanging(value);
					this.SendPropertyChanging();
					this._soper = value;
					this.SendPropertyChanged("soper");
					this.OnsoperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOP", DbType="NVarChar(50)")]
		public string idOP
		{
			get
			{
				return this._idOP;
			}
			set
			{
				if ((this._idOP != value))
				{
					this.OnidOPChanging(value);
					this.SendPropertyChanging();
					this._idOP = value;
					this.SendPropertyChanged("idOP");
					this.OnidOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleOP", DbType="NVarChar(50)")]
		public string TitleOP
		{
			get
			{
				return this._TitleOP;
			}
			set
			{
				if ((this._TitleOP != value))
				{
					this.OnTitleOPChanging(value);
					this.SendPropertyChanging();
					this._TitleOP = value;
					this.SendPropertyChanged("TitleOP");
					this.OnTitleOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOP", DbType="NVarChar(10)")]
		public string TypeOP
		{
			get
			{
				return this._TypeOP;
			}
			set
			{
				if ((this._TypeOP != value))
				{
					this.OnTypeOPChanging(value);
					this.SendPropertyChanging();
					this._TypeOP = value;
					this.SendPropertyChanged("TypeOP");
					this.OnTypeOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGroup", DbType="NVarChar(50)")]
		public string sGroup
		{
			get
			{
				return this._sGroup;
			}
			set
			{
				if ((this._sGroup != value))
				{
					this.OnsGroupChanging(value);
					this.SendPropertyChanging();
					this._sGroup = value;
					this.SendPropertyChanged("sGroup");
					this.OnsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saffiliation", DbType="NVarChar(10)")]
		public string saffiliation
		{
			get
			{
				return this._saffiliation;
			}
			set
			{
				if ((this._saffiliation != value))
				{
					this.OnsaffiliationChanging(value);
					this.SendPropertyChanging();
					this._saffiliation = value;
					this.SendPropertyChanged("saffiliation");
					this.OnsaffiliationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ishare", DbType="Int")]
		public System.Nullable<int> ishare
		{
			get
			{
				return this._ishare;
			}
			set
			{
				if ((this._ishare != value))
				{
					this.OnishareChanging(value);
					this.SendPropertyChanging();
					this._ishare = value;
					this.SendPropertyChanged("ishare");
					this.OnishareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XWGS", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> XWGS
		{
			get
			{
				return this._XWGS;
			}
			set
			{
				if ((this._XWGS != value))
				{
					this.OnXWGSChanging(value);
					this.SendPropertyChanging();
					this._XWGS = value;
					this.SendPropertyChanged("XWGS");
					this.OnXWGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YWGS", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> YWGS
		{
			get
			{
				return this._YWGS;
			}
			set
			{
				if ((this._YWGS != value))
				{
					this.OnYWGSChanging(value);
					this.SendPropertyChanging();
					this._YWGS = value;
					this.SendPropertyChanged("YWGS");
					this.OnYWGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HRel", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> HRel
		{
			get
			{
				return this._HRel;
			}
			set
			{
				if ((this._HRel != value))
				{
					this.OnHRelChanging(value);
					this.SendPropertyChanging();
					this._HRel = value;
					this.SendPropertyChanged("HRel");
					this.OnHRelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzimuthB", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AzimuthB
		{
			get
			{
				return this._AzimuthB;
			}
			set
			{
				if ((this._AzimuthB != value))
				{
					this.OnAzimuthBChanging(value);
					this.SendPropertyChanging();
					this._AzimuthB = value;
					this.SendPropertyChanged("AzimuthB");
					this.OnAzimuthBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzimuthE", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AzimuthE
		{
			get
			{
				return this._AzimuthE;
			}
			set
			{
				if ((this._AzimuthE != value))
				{
					this.OnAzimuthEChanging(value);
					this.SendPropertyChanging();
					this._AzimuthE = value;
					this.SendPropertyChanged("AzimuthE");
					this.OnAzimuthEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglMinH", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AnglMinH
		{
			get
			{
				return this._AnglMinH;
			}
			set
			{
				if ((this._AnglMinH != value))
				{
					this.OnAnglMinHChanging(value);
					this.SendPropertyChanging();
					this._AnglMinH = value;
					this.SendPropertyChanged("AnglMinH");
					this.OnAnglMinHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglMaxH", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AnglMaxH
		{
			get
			{
				return this._AnglMaxH;
			}
			set
			{
				if ((this._AnglMaxH != value))
				{
					this.OnAnglMaxHChanging(value);
					this.SendPropertyChanging();
					this._AnglMaxH = value;
					this.SendPropertyChanged("AnglMaxH");
					this.OnAnglMaxHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzimuthMainAxis", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AzimuthMainAxis
		{
			get
			{
				return this._AzimuthMainAxis;
			}
			set
			{
				if ((this._AzimuthMainAxis != value))
				{
					this.OnAzimuthMainAxisChanging(value);
					this.SendPropertyChanging();
					this._AzimuthMainAxis = value;
					this.SendPropertyChanged("AzimuthMainAxis");
					this.OnAzimuthMainAxisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AngFrameH", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AngFrameH
		{
			get
			{
				return this._AngFrameH;
			}
			set
			{
				if ((this._AngFrameH != value))
				{
					this.OnAngFrameHChanging(value);
					this.SendPropertyChanging();
					this._AngFrameH = value;
					this.SendPropertyChanged("AngFrameH");
					this.OnAngFrameHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglFrameV", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AnglFrameV
		{
			get
			{
				return this._AnglFrameV;
			}
			set
			{
				if ((this._AnglFrameV != value))
				{
					this.OnAnglFrameVChanging(value);
					this.SendPropertyChanging();
					this._AnglFrameV = value;
					this.SendPropertyChanged("AnglFrameV");
					this.OnAnglFrameVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglCameraRotationH", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AnglCameraRotationH
		{
			get
			{
				return this._AnglCameraRotationH;
			}
			set
			{
				if ((this._AnglCameraRotationH != value))
				{
					this.OnAnglCameraRotationHChanging(value);
					this.SendPropertyChanging();
					this._AnglCameraRotationH = value;
					this.SendPropertyChanged("AnglCameraRotationH");
					this.OnAnglCameraRotationHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglCameraRotationV", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> AnglCameraRotationV
		{
			get
			{
				return this._AnglCameraRotationV;
			}
			set
			{
				if ((this._AnglCameraRotationV != value))
				{
					this.OnAnglCameraRotationVChanging(value);
					this.SendPropertyChanging();
					this._AnglCameraRotationV = value;
					this.SendPropertyChanged("AnglCameraRotationV");
					this.OnAnglCameraRotationVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableHeightUpper", DbType="Float NOT NULL")]
		public double AvailableHeightUpper
		{
			get
			{
				return this._AvailableHeightUpper;
			}
			set
			{
				if ((this._AvailableHeightUpper != value))
				{
					this.OnAvailableHeightUpperChanging(value);
					this.SendPropertyChanging();
					this._AvailableHeightUpper = value;
					this.SendPropertyChanged("AvailableHeightUpper");
					this.OnAvailableHeightUpperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableHeightLover", DbType="Float NOT NULL")]
		public double AvailableHeightLover
		{
			get
			{
				return this._AvailableHeightLover;
			}
			set
			{
				if ((this._AvailableHeightLover != value))
				{
					this.OnAvailableHeightLoverChanging(value);
					this.SendPropertyChanging();
					this._AvailableHeightLover = value;
					this.SendPropertyChanged("AvailableHeightLover");
					this.OnAvailableHeightLoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dto", DbType="DateTime2")]
		public System.Nullable<System.DateTime> dto
		{
			get
			{
				return this._dto;
			}
			set
			{
				if ((this._dto != value))
				{
					this.OndtoChanging(value);
					this.SendPropertyChanging();
					this._dto = value;
					this.SendPropertyChanged("dto");
					this.OndtoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MILSP_VISIBLE_OBSERVPOINTS")]
	public partial class VisiblilityObservPoint : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OBJECTID;
		
		private string _soper;
		
		private string _idOP;
		
		private string _TitleOP;
		
		private string _TypeOP;
		
		private string _sGroup;
		
		private string _saffiliation;
		
		private System.Nullable<int> _ishare;
		
		private System.Nullable<double> _XWGS;
		
		private System.Nullable<double> _YWGS;
		
		private System.Nullable<double> _HRel;
		
		private System.Nullable<double> _AzimuthB;
		
		private System.Nullable<double> _AzimuthE;
		
		private System.Nullable<double> _AnglMinH;
		
		private System.Nullable<double> _AnglMaxH;
		
		private System.Nullable<double> _AzimuthMainAxis;
		
		private System.Nullable<double> _AngFrameH;
		
		private System.Nullable<double> _AnglFrameV;
		
		private System.Nullable<double> _AnglCameraRotationH;
		
		private System.Nullable<double> _AnglCameraRotationV;
		
		private double _AvailableHeightUpper;
		
		private double _AvailableHeightLover;
		
		private System.Nullable<System.DateTime> _dto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTIDChanging(int value);
    partial void OnOBJECTIDChanged();
    partial void OnsoperChanging(string value);
    partial void OnsoperChanged();
    partial void OnidOPChanging(string value);
    partial void OnidOPChanged();
    partial void OnTitleOPChanging(string value);
    partial void OnTitleOPChanged();
    partial void OnTypeOPChanging(string value);
    partial void OnTypeOPChanged();
    partial void OnsGroupChanging(string value);
    partial void OnsGroupChanged();
    partial void OnsaffiliationChanging(string value);
    partial void OnsaffiliationChanged();
    partial void OnishareChanging(System.Nullable<int> value);
    partial void OnishareChanged();
    partial void OnXWGSChanging(System.Nullable<double> value);
    partial void OnXWGSChanged();
    partial void OnYWGSChanging(System.Nullable<double> value);
    partial void OnYWGSChanged();
    partial void OnHRelChanging(System.Nullable<double> value);
    partial void OnHRelChanged();
    partial void OnAzimuthBChanging(System.Nullable<double> value);
    partial void OnAzimuthBChanged();
    partial void OnAzimuthEChanging(System.Nullable<double> value);
    partial void OnAzimuthEChanged();
    partial void OnAnglMinHChanging(System.Nullable<double> value);
    partial void OnAnglMinHChanged();
    partial void OnAnglMaxHChanging(System.Nullable<double> value);
    partial void OnAnglMaxHChanged();
    partial void OnAzimuthMainAxisChanging(System.Nullable<double> value);
    partial void OnAzimuthMainAxisChanged();
    partial void OnAngFrameHChanging(System.Nullable<double> value);
    partial void OnAngFrameHChanged();
    partial void OnAnglFrameVChanging(System.Nullable<double> value);
    partial void OnAnglFrameVChanged();
    partial void OnAnglCameraRotationHChanging(System.Nullable<double> value);
    partial void OnAnglCameraRotationHChanged();
    partial void OnAnglCameraRotationVChanging(System.Nullable<double> value);
    partial void OnAnglCameraRotationVChanged();
    partial void OnAvailableHeightUpperChanging(double value);
    partial void OnAvailableHeightUpperChanged();
    partial void OnAvailableHeightLoverChanging(double value);
    partial void OnAvailableHeightLoverChanged();
    partial void OndtoChanging(System.Nullable<System.DateTime> value);
    partial void OndtoChanged();
    #endregion
		
		public VisiblilityObservPoint()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this.OnOBJECTIDChanging(value);
					this.SendPropertyChanging();
					this._OBJECTID = value;
					this.SendPropertyChanged("OBJECTID");
					this.OnOBJECTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soper", DbType="NVarChar(50)")]
		public string soper
		{
			get
			{
				return this._soper;
			}
			set
			{
				if ((this._soper != value))
				{
					this.OnsoperChanging(value);
					this.SendPropertyChanging();
					this._soper = value;
					this.SendPropertyChanged("soper");
					this.OnsoperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOP", DbType="NVarChar(50)")]
		public string idOP
		{
			get
			{
				return this._idOP;
			}
			set
			{
				if ((this._idOP != value))
				{
					this.OnidOPChanging(value);
					this.SendPropertyChanging();
					this._idOP = value;
					this.SendPropertyChanged("idOP");
					this.OnidOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleOP", DbType="NVarChar(50)")]
		public string TitleOP
		{
			get
			{
				return this._TitleOP;
			}
			set
			{
				if ((this._TitleOP != value))
				{
					this.OnTitleOPChanging(value);
					this.SendPropertyChanging();
					this._TitleOP = value;
					this.SendPropertyChanged("TitleOP");
					this.OnTitleOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOP", DbType="NVarChar(10)")]
		public string TypeOP
		{
			get
			{
				return this._TypeOP;
			}
			set
			{
				if ((this._TypeOP != value))
				{
					this.OnTypeOPChanging(value);
					this.SendPropertyChanging();
					this._TypeOP = value;
					this.SendPropertyChanged("TypeOP");
					this.OnTypeOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGroup", DbType="NVarChar(50)")]
		public string sGroup
		{
			get
			{
				return this._sGroup;
			}
			set
			{
				if ((this._sGroup != value))
				{
					this.OnsGroupChanging(value);
					this.SendPropertyChanging();
					this._sGroup = value;
					this.SendPropertyChanged("sGroup");
					this.OnsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saffiliation", DbType="NVarChar(10)")]
		public string saffiliation
		{
			get
			{
				return this._saffiliation;
			}
			set
			{
				if ((this._saffiliation != value))
				{
					this.OnsaffiliationChanging(value);
					this.SendPropertyChanging();
					this._saffiliation = value;
					this.SendPropertyChanged("saffiliation");
					this.OnsaffiliationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ishare", DbType="Int")]
		public System.Nullable<int> ishare
		{
			get
			{
				return this._ishare;
			}
			set
			{
				if ((this._ishare != value))
				{
					this.OnishareChanging(value);
					this.SendPropertyChanging();
					this._ishare = value;
					this.SendPropertyChanged("ishare");
					this.OnishareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XWGS", DbType="Float")]
		public System.Nullable<double> XWGS
		{
			get
			{
				return this._XWGS;
			}
			set
			{
				if ((this._XWGS != value))
				{
					this.OnXWGSChanging(value);
					this.SendPropertyChanging();
					this._XWGS = value;
					this.SendPropertyChanged("XWGS");
					this.OnXWGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YWGS", DbType="Float")]
		public System.Nullable<double> YWGS
		{
			get
			{
				return this._YWGS;
			}
			set
			{
				if ((this._YWGS != value))
				{
					this.OnYWGSChanging(value);
					this.SendPropertyChanging();
					this._YWGS = value;
					this.SendPropertyChanged("YWGS");
					this.OnYWGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HRel", DbType="Float")]
		public System.Nullable<double> HRel
		{
			get
			{
				return this._HRel;
			}
			set
			{
				if ((this._HRel != value))
				{
					this.OnHRelChanging(value);
					this.SendPropertyChanging();
					this._HRel = value;
					this.SendPropertyChanged("HRel");
					this.OnHRelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzimuthB", DbType="Float")]
		public System.Nullable<double> AzimuthB
		{
			get
			{
				return this._AzimuthB;
			}
			set
			{
				if ((this._AzimuthB != value))
				{
					this.OnAzimuthBChanging(value);
					this.SendPropertyChanging();
					this._AzimuthB = value;
					this.SendPropertyChanged("AzimuthB");
					this.OnAzimuthBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzimuthE", DbType="Float")]
		public System.Nullable<double> AzimuthE
		{
			get
			{
				return this._AzimuthE;
			}
			set
			{
				if ((this._AzimuthE != value))
				{
					this.OnAzimuthEChanging(value);
					this.SendPropertyChanging();
					this._AzimuthE = value;
					this.SendPropertyChanged("AzimuthE");
					this.OnAzimuthEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglMinH", DbType="Float")]
		public System.Nullable<double> AnglMinH
		{
			get
			{
				return this._AnglMinH;
			}
			set
			{
				if ((this._AnglMinH != value))
				{
					this.OnAnglMinHChanging(value);
					this.SendPropertyChanging();
					this._AnglMinH = value;
					this.SendPropertyChanged("AnglMinH");
					this.OnAnglMinHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglMaxH", DbType="Float")]
		public System.Nullable<double> AnglMaxH
		{
			get
			{
				return this._AnglMaxH;
			}
			set
			{
				if ((this._AnglMaxH != value))
				{
					this.OnAnglMaxHChanging(value);
					this.SendPropertyChanging();
					this._AnglMaxH = value;
					this.SendPropertyChanged("AnglMaxH");
					this.OnAnglMaxHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzimuthMainAxis", DbType="Float")]
		public System.Nullable<double> AzimuthMainAxis
		{
			get
			{
				return this._AzimuthMainAxis;
			}
			set
			{
				if ((this._AzimuthMainAxis != value))
				{
					this.OnAzimuthMainAxisChanging(value);
					this.SendPropertyChanging();
					this._AzimuthMainAxis = value;
					this.SendPropertyChanged("AzimuthMainAxis");
					this.OnAzimuthMainAxisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AngFrameH", DbType="Float")]
		public System.Nullable<double> AngFrameH
		{
			get
			{
				return this._AngFrameH;
			}
			set
			{
				if ((this._AngFrameH != value))
				{
					this.OnAngFrameHChanging(value);
					this.SendPropertyChanging();
					this._AngFrameH = value;
					this.SendPropertyChanged("AngFrameH");
					this.OnAngFrameHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglFrameV", DbType="Float")]
		public System.Nullable<double> AnglFrameV
		{
			get
			{
				return this._AnglFrameV;
			}
			set
			{
				if ((this._AnglFrameV != value))
				{
					this.OnAnglFrameVChanging(value);
					this.SendPropertyChanging();
					this._AnglFrameV = value;
					this.SendPropertyChanged("AnglFrameV");
					this.OnAnglFrameVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglCameraRotationH", DbType="Float")]
		public System.Nullable<double> AnglCameraRotationH
		{
			get
			{
				return this._AnglCameraRotationH;
			}
			set
			{
				if ((this._AnglCameraRotationH != value))
				{
					this.OnAnglCameraRotationHChanging(value);
					this.SendPropertyChanging();
					this._AnglCameraRotationH = value;
					this.SendPropertyChanged("AnglCameraRotationH");
					this.OnAnglCameraRotationHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnglCameraRotationV", DbType="Float")]
		public System.Nullable<double> AnglCameraRotationV
		{
			get
			{
				return this._AnglCameraRotationV;
			}
			set
			{
				if ((this._AnglCameraRotationV != value))
				{
					this.OnAnglCameraRotationVChanging(value);
					this.SendPropertyChanging();
					this._AnglCameraRotationV = value;
					this.SendPropertyChanged("AnglCameraRotationV");
					this.OnAnglCameraRotationVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableHeightUpper", DbType="Float NOT NULL")]
		public double AvailableHeightUpper
		{
			get
			{
				return this._AvailableHeightUpper;
			}
			set
			{
				if ((this._AvailableHeightUpper != value))
				{
					this.OnAvailableHeightUpperChanging(value);
					this.SendPropertyChanging();
					this._AvailableHeightUpper = value;
					this.SendPropertyChanged("AvailableHeightUpper");
					this.OnAvailableHeightUpperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableHeightLover", DbType="Float NOT NULL")]
		public double AvailableHeightLover
		{
			get
			{
				return this._AvailableHeightLover;
			}
			set
			{
				if ((this._AvailableHeightLover != value))
				{
					this.OnAvailableHeightLoverChanging(value);
					this.SendPropertyChanging();
					this._AvailableHeightLover = value;
					this.SendPropertyChanged("AvailableHeightLover");
					this.OnAvailableHeightLoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dto", DbType="DateTime2")]
		public System.Nullable<System.DateTime> dto
		{
			get
			{
				return this._dto;
			}
			set
			{
				if ((this._dto != value))
				{
					this.OndtoChanging(value);
					this.SendPropertyChanging();
					this._dto = value;
					this.SendPropertyChanged("dto");
					this.OndtoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
