<?xml version="1.0" encoding="utf-8"?><Database Name="MilSpaceApp" Class="MilSpaceStorageContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SPAERO01\SQLEXPRESS;Initial Catalog=MilSpaceApp;Integrated Security=True" SettingsObjectName="MilSpace.DataAccess.Properties.Settings" SettingsPropertyName="MilSpaceAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MilSp_Session" Member="MilSp_Sessions" AccessModifier="Internal">
    <Type Name="MilSp_Session" AccessModifier="Internal">
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfileId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="MilSp_Profile_MilSp_Session" Member="MilSp_Profile" ThisKey="ProfileId" OtherKey="idRow" Type="MilSp_Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Profile" Member="MilSp_Profiles" AccessModifier="Internal">
    <Type Name="MilSp_Profile" AccessModifier="Internal">
      <Column Name="idRow" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfileName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileData" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Shared" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Creator" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MilSp_Profile_MilSp_Session" Member="MilSp_Sessions" ThisKey="idRow" OtherKey="ProfileId" Type="MilSp_Session" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ObservPoints" Member="VisiblilityObservPoints" AccessModifier="Internal">
    <Type Name="VisiblilityObservPoint" AccessModifier="Internal">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TitleOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeOP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="saffiliation" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ishare" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HRel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AzimuthB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AzimuthE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglMinH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglMaxH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AzimuthMainAxis" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AngFrameH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglFrameV" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglCameraRotationH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglCameraRotationV" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dto" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soper" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>