<?xml version="1.0" encoding="utf-8"?><Database Name="DNOEGDB" Class="MilSpaceVisibilityContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=DNOEGDB;Integrated Security=True" SettingsObjectName="MilSpace.DataAccess.Properties.Settings" SettingsPropertyName="DNOEGDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MilSp_Visible_ResultIOP" Member="MilSp_Visible_ResultIOPs">
    <Type Name="MilSp_Visible_ResultIOP">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idOPRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idIOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HAbs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_InstantObservationPoint" Member="MilSp_Visible_InstantObservationPoints">
    <Type Name="MilSp_Visible_InstantObservationPoint">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idIOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDOP" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="HAbs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Az2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Angl2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultsCover" Member="MilSp_Visible_ResultsCovers">
    <Type Name="MilSp_Visible_ResultsCover">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCover" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LnkToCover" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ColorCover" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoDataCover" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_CL_TypeOP" Member="MilSp_CL_TypeOPs">
    <Type Name="MilSp_CL_TypeOP">
      <Column Name="objectid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeOP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultOO" Member="MilSp_Visible_ResultOOs">
    <Type Name="MilSp_Visible_ResultOO">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MilSp_Visible_ResultQuality" Member="MilSp_Visible_ResultQuality_s">
    <Type Name="MilSp_Visible_ResultQuality_">
      <Column Name="objectid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idResQual" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDOORes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDOPRes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeQual" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EvalQual" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MILSP_VISIBILITY_TASK" Member="MilSp_VisibilityTasks" AccessModifier="Internal">
    <Type Name="MilSp_VisibilityTask" AccessModifier="Internal">
      <Column Name="IdRow" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Started" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Finished" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CalculatedResults" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReferencedGDB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="surface" Member="Surface" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CalcType" Member="CalculationType" Type="System.Int32" DbType="Int" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MILSP_VISIBLE_OBSERVPOINTS" Member="VisiblilityObservPoints" AccessModifier="Internal">
    <Type Name="VisiblilityObservPoint" AccessModifier="Internal">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soper" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TitleOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeOP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="saffiliation" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ishare" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YWGS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HRel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AzimuthB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AzimuthE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglMinH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglMaxH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AzimuthMainAxis" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AngFrameH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglFrameV" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglCameraRotationH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnglCameraRotationV" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AvailableHeightUpper" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AvailableHeightLover" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="dto" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="InnerRadius" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OuterRadius" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MILSP_VISIBLE_OBJECTSOBSERVATION_R" Member="VisiblilityObservationObjects" AccessModifier="Internal">
    <Type Name="VisiblilityObservationObjects" AccessModifier="Internal">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DTO" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="idOO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sGroupOO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTitleOO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ifShare" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soper" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="saffiliation" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MILSP_VISIBLE_RESULTS" Member="MilSp_VisiblityResults" AccessModifier="Internal">
    <Type Name="MilSp_VisiblityResults" AccessModifier="Internal">
      <Column Name="IdRow" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CalcType" Member="CalculationType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CalculatedResults" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReferencedGDB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="shared" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="surface" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MILSP_VISIBILITY_USER_SESSION" Member="MilSp_VisibilityUserSessions" AccessModifier="Internal">
    <Type Name="MilSp_VisibilityUserSession" AccessModifier="Internal">
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="visibilityResultId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>