#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilSpace.DataAccess.Definition
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MilSpaceApp")]
	public partial class MilSpaceStorageContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MilSpaceStorageContext() : 
				base(global::MilSpace.DataAccess.Properties.Settings.Default.MilSpaceAppConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MilSpaceStorageContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		internal System.Data.Linq.Table<MilSp_Profile> MilSp_Profiles
		{
			get
			{
				return this.GetTable<MilSp_Profile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MilSp_Profile")]
	internal partial class MilSp_Profile
	{
		
		private int _idRow;
		
		private string _ProfileName;
		
		private string _ProfileData;
		
		public MilSp_Profile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRow", DbType="Int NOT NULL")]
		public int idRow
		{
			get
			{
				return this._idRow;
			}
			set
			{
				if ((this._idRow != value))
				{
					this._idRow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileName", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ProfileName
		{
			get
			{
				return this._ProfileName;
			}
			set
			{
				if ((this._ProfileName != value))
				{
					this._ProfileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileData", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ProfileData
		{
			get
			{
				return this._ProfileData;
			}
			set
			{
				if ((this._ProfileData != value))
				{
					this._ProfileData = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
